import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    globalMargin: {
        marginHorizontal: 20,
    },
    container: {
        flex: 1,
    },
    flex: {
        flexWrap: 'wrap',
        flexDirection: 'row',
    },
    center: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    text: {
        fontFamily: 'Helvetica',
        color: '#01192E',
        fontSize: 14,
    },
    textbold: {
        fontFamily: 'Helvetica-Bold',
        color: '#01192E',
        fontWeight: '500',
    },
    h1: {
        fontSize: 60,
        fontFamily: 'Helvetica-Bold',
        color: '#01192E',
        fontWeight: '500',
    },
    h2: {
        fontSize: 45,
        fontFamily: 'Helvetica-Bold',
        color: '#01192E',
        fontWeight: '600',
    },
    h3: {
        fontSize: 23,
        fontFamily: 'Helvetica-Bold',
        color: '#01192E',
        fontWeight: '600',
    },
    h4: {
        fontSize: 18,
        fontFamily: 'Helvetica-Bold',
        color: '#01192E',
    },
    h6: {
        fontSize: 16,
        fontFamily: 'Helvetica-Bold',
        color: '#01192E',
    },
    h7: {
        fontSize: 14,
        fontFamily: 'Helvetica-Bold',
        color: '#01192E',
    },
    h5: {
        fontFamily: 'Helvetica-Bold',
    },
    orange: {
        color: '#FC702A',
    },
    textb: {
        fontWeight: '300',
        fontSize: 15,
    },
    button: {
        borderWidth: 1,
        borderColor: '#01192E',
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 8,
        alignItems: 'center',
    },
    input: {
        backgroundColor: 'white',
        borderRadius: 8,
        paddingHorizontal: 20,
        paddingVertical: 10,
        width: 250,
        marginHorizontal: 'auto',
        shadowColor: '#4d4d4d',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 6,
    },
    shadow: {
        shadowColor: '#4d4d4d',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        backgroundColor: 'white',
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 6,
        borderRadius: 4,
    },
    textinput: {
        fontFamily: 'Helvetica',
        color: '#000000',
        fontSize: 14,
        paddingVertical: 2,
    },
    iconinput: {
        position: 'absolute',
        flex: 1,
        right: 0,
        top: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'flex-end',
        paddingRight: 15,
    },
    link: {
        color: '#5c71ad',
        fontSize: 11,
        fontFamily: 'Helvetica',
    },
    linkPad: {
        color: '#5c71ad',
        fontSize: 11,
        fontWeight: '300',
        paddingHorizontal: 15,
        paddingVertical: 8,
    },
    textGrayPad: {
        color: '#borderTopWidth',
        fontSize: 11,
        fontWeight: '300',
        paddingHorizontal: 15,
        paddingVertical: 8,
        width: 270,
    },
    textGray: {
        fontFamily: 'Helvetica',
        color: '#707070',
        fontSize: 13,
        fontWeight: '300',
    },
    user: {
        fontFamily: 'Helvetica-Bold',
        fontWeight: '600',
        color: '#01192E',
        fontSize: 16,
    },
    user_reply: {
        fontFamily: 'Helvetica-Bold',
        fontWeight: '600',
        color: '#67737D',
        fontSize: 13,
    },
    msg: {
        fontFamily: 'Helvetica',
        fontSize: 14,
        textAlign: 'left',
        flexShrink: 1,
        width: '100%',
    },
    numberGray: {
        fontFamily: 'Helvetica',
        fontSize: 12,
        color: '#bebebe',
        marginLeft: 3,
    },
    backmodal: {
        flex: 1,
        backgroundColor: '#6363635c',
        justifyContent: 'center',
        alignItems: 'center',
    },
    button_user: {
        justifyContent: 'center',
        flexDirection: 'row',
        paddingVertical: 2,
        alignSelf: 'flex-start',
    },
    arrow_back: {
        alignItems: 'center',
        justifyContent: 'center',
        position: 'absolute',
        left: 5,
        top: 0,
        bottom: 0,
    },
    shadow_button: {
        shadowColor: '#4d4d4d',
        shadowOffset: {
            width: 2,
            height: 3,
        },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 6,
    },
    error: {
        color: '#9b0000',
    },
    flex_center: {
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
    },
    flex_start: {
        alignItems: 'center',
        justifyContent: 'flex-start',
        flexDirection: 'row',
    },
    flex_spc_between: {
        alignItems: 'center',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        flexDirection: 'row',
    },
    button_container: {
        flexDirection: 'row',
        paddingHorizontal: 8,
        paddingVertical: 2,
        backgroundColor: '#E8E8E8',
        marginRight: 10,
        borderRadius: 6,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 23,
    },
    text_button: {
        fontFamily: 'Helvetica',
        fontSize: 12,
        color: '#67737D',
    },
    flex_container: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'center',
    },
    idea_msg: {
        fontFamily: 'Helvetica',
        color: '#01192E',
        fontSize: 14,
        textAlign: 'left',
        flexShrink: 1,
    },
    number: {
        fontFamily: 'Helvetica',
        fontSize: 12,
        color: '#B9B9B9',
        marginLeft: 1,
    },
    corner: {
        position: 'absolute',
        top: -2,
        right: -26,
        transform: [{ rotate: '45deg' }],
        backgroundColor: '#01192E',
        paddingTop: 8,
        paddingBottom: 4,
        paddingHorizontal: 30,
    },
    corner_container: {
        borderTopRightRadius: 14,
        position: 'absolute',
        height: 40,
        left: 0,
        right: 0,
        overflow: 'hidden',
    },
    container_abs: {
        position: 'absolute',
        bottom: -2,
        right: 0,
    },
    white_wrap: {
        backgroundColor: 'white',
        borderRadius: 14,
        shadowColor: '#4d4d4d',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 6,
    },
    idea_label: {
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        backgroundColor: '#E8E8E8',
        borderRadius: 3,
        paddingHorizontal: 4,
        paddingVertical: 3,
        alignSelf: 'flex-start',
    },
    white_idea_wrap: {
        backgroundColor: 'white',
        borderRadius: 14,
        shadowColor: '#4d4d4d',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 6,
        marginVertical: 8,
        width: '92%',
    },
    idea_subwrap: {
        paddingTop: 15,
        paddingBottom: 6,
        paddingHorizontal: 25,
        borderRadius: 14,
    },
});
